[package]
name = "pyo3-demo"
version = "0.1.0"
authors = ["wangyi <wangyi@megvii.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
numpy = "0.14.1"
pyo3 = "0.14.1"
